require('dotenv').config();
const { MongoClient } = require('mongodb');

async function run() {
  const uri = process.env.MONGO_URI;
  if (!uri) {
    console.error('MONGO_URI not set');
    process.exit(1);
  }

  const client = new MongoClient(uri);
  try {
    await client.connect();
    const db = client.db('campushub');

    const course = {
      title: 'Test Course — Intro to Testing',
      description: 'Autogenerated test course created by script',
      teacherName: 'Automated Insert',
      credits: 3,
      grade: 'Grade 10A',
      createdAt: new Date(),
    };

    const courseResult = await db.collection('courses').insertOne(course);
    console.log('Inserted course id:', courseResult.insertedId.toString());

    const timetableItem = {
      courseId: courseResult.insertedId.toString(),
      day: 'Mon',
      time: '10:00',
      subject: course.title,
      room: '101',
      teacher: course.teacherName,
      grade: course.grade,
    };

    const ttResult = await db.collection('timetable').insertOne(timetableItem);
    console.log('Inserted timetable id:', ttResult.insertedId.toString());

    const createdCourse = await db.collection('courses').findOne({ _id: courseResult.insertedId });
    const createdTT = await db.collection('timetable').find({ courseId: courseResult.insertedId.toString() }).toArray();

    console.log('Created course:', createdCourse);
    console.log('Timetable entries for course:', createdTT);

    await client.close();
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

run();
