/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TakeAttendanceRouteImport } from './routes/take-attendance'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PayslipsRouteImport } from './routes/payslips'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as MyLeaveRouteImport } from './routes/my-leave'
import { Route as MyGradesRouteImport } from './routes/my-grades'
import { Route as MyFeesRouteImport } from './routes/my-fees'
import { Route as MyCoursesRouteImport } from './routes/my-courses'
import { Route as MyClassesRouteImport } from './routes/my-classes'
import { Route as MyAttendanceRouteImport } from './routes/my-attendance'
import { Route as MyAssignmentsRouteImport } from './routes/my-assignments'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InquiriesRouteImport } from './routes/inquiries'
import { Route as GradebookRouteImport } from './routes/gradebook'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EnrollmentRouteImport } from './routes/enrollment'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as IndexRouteImport } from './routes/index'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeAttendanceRoute = TakeAttendanceRouteImport.update({
  id: '/take-attendance',
  path: '/take-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PayslipsRoute = PayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLeaveRoute = MyLeaveRouteImport.update({
  id: '/my-leave',
  path: '/my-leave',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGradesRoute = MyGradesRouteImport.update({
  id: '/my-grades',
  path: '/my-grades',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFeesRoute = MyFeesRouteImport.update({
  id: '/my-fees',
  path: '/my-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesRoute = MyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const MyClassesRoute = MyClassesRouteImport.update({
  id: '/my-classes',
  path: '/my-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAttendanceRoute = MyAttendanceRouteImport.update({
  id: '/my-attendance',
  path: '/my-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAssignmentsRoute = MyAssignmentsRouteImport.update({
  id: '/my-assignments',
  path: '/my-assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesRoute = InquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const GradebookRoute = GradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentRoute = EnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/assignments': typeof AssignmentsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/enrollment': typeof EnrollmentRoute
  '/events': typeof EventsRoute
  '/fees': typeof FeesRoute
  '/gradebook': typeof GradebookRoute
  '/inquiries': typeof InquiriesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-assignments': typeof MyAssignmentsRoute
  '/my-attendance': typeof MyAttendanceRoute
  '/my-classes': typeof MyClassesRoute
  '/my-courses': typeof MyCoursesRoute
  '/my-fees': typeof MyFeesRoute
  '/my-grades': typeof MyGradesRoute
  '/my-leave': typeof MyLeaveRoute
  '/my-profile': typeof MyProfileRoute
  '/payslips': typeof PayslipsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/take-attendance': typeof TakeAttendanceRoute
  '/tasks': typeof TasksRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/assignments': typeof AssignmentsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/enrollment': typeof EnrollmentRoute
  '/events': typeof EventsRoute
  '/fees': typeof FeesRoute
  '/gradebook': typeof GradebookRoute
  '/inquiries': typeof InquiriesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-assignments': typeof MyAssignmentsRoute
  '/my-attendance': typeof MyAttendanceRoute
  '/my-classes': typeof MyClassesRoute
  '/my-courses': typeof MyCoursesRoute
  '/my-fees': typeof MyFeesRoute
  '/my-grades': typeof MyGradesRoute
  '/my-leave': typeof MyLeaveRoute
  '/my-profile': typeof MyProfileRoute
  '/payslips': typeof PayslipsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/take-attendance': typeof TakeAttendanceRoute
  '/tasks': typeof TasksRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/assignments': typeof AssignmentsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/enrollment': typeof EnrollmentRoute
  '/events': typeof EventsRoute
  '/fees': typeof FeesRoute
  '/gradebook': typeof GradebookRoute
  '/inquiries': typeof InquiriesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-assignments': typeof MyAssignmentsRoute
  '/my-attendance': typeof MyAttendanceRoute
  '/my-classes': typeof MyClassesRoute
  '/my-courses': typeof MyCoursesRoute
  '/my-fees': typeof MyFeesRoute
  '/my-grades': typeof MyGradesRoute
  '/my-leave': typeof MyLeaveRoute
  '/my-profile': typeof MyProfileRoute
  '/payslips': typeof PayslipsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/take-attendance': typeof TakeAttendanceRoute
  '/tasks': typeof TasksRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academics'
    | '/admissions'
    | '/analytics'
    | '/announcements'
    | '/assignments'
    | '/audit'
    | '/dashboard'
    | '/documents'
    | '/enrollment'
    | '/events'
    | '/fees'
    | '/gradebook'
    | '/inquiries'
    | '/library'
    | '/login'
    | '/messages'
    | '/my-assignments'
    | '/my-attendance'
    | '/my-classes'
    | '/my-courses'
    | '/my-fees'
    | '/my-grades'
    | '/my-leave'
    | '/my-profile'
    | '/payslips'
    | '/settings'
    | '/staff'
    | '/students'
    | '/take-attendance'
    | '/tasks'
    | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academics'
    | '/admissions'
    | '/analytics'
    | '/announcements'
    | '/assignments'
    | '/audit'
    | '/dashboard'
    | '/documents'
    | '/enrollment'
    | '/events'
    | '/fees'
    | '/gradebook'
    | '/inquiries'
    | '/library'
    | '/login'
    | '/messages'
    | '/my-assignments'
    | '/my-attendance'
    | '/my-classes'
    | '/my-courses'
    | '/my-fees'
    | '/my-grades'
    | '/my-leave'
    | '/my-profile'
    | '/payslips'
    | '/settings'
    | '/staff'
    | '/students'
    | '/take-attendance'
    | '/tasks'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/academics'
    | '/admissions'
    | '/analytics'
    | '/announcements'
    | '/assignments'
    | '/audit'
    | '/dashboard'
    | '/documents'
    | '/enrollment'
    | '/events'
    | '/fees'
    | '/gradebook'
    | '/inquiries'
    | '/library'
    | '/login'
    | '/messages'
    | '/my-assignments'
    | '/my-attendance'
    | '/my-classes'
    | '/my-courses'
    | '/my-fees'
    | '/my-grades'
    | '/my-leave'
    | '/my-profile'
    | '/payslips'
    | '/settings'
    | '/staff'
    | '/students'
    | '/take-attendance'
    | '/tasks'
    | '/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AssignmentsRoute: typeof AssignmentsRoute
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  EnrollmentRoute: typeof EnrollmentRoute
  EventsRoute: typeof EventsRoute
  FeesRoute: typeof FeesRoute
  GradebookRoute: typeof GradebookRoute
  InquiriesRoute: typeof InquiriesRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MyAssignmentsRoute: typeof MyAssignmentsRoute
  MyAttendanceRoute: typeof MyAttendanceRoute
  MyClassesRoute: typeof MyClassesRoute
  MyCoursesRoute: typeof MyCoursesRoute
  MyFeesRoute: typeof MyFeesRoute
  MyGradesRoute: typeof MyGradesRoute
  MyLeaveRoute: typeof MyLeaveRoute
  MyProfileRoute: typeof MyProfileRoute
  PayslipsRoute: typeof PayslipsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  StudentsRoute: typeof StudentsRoute
  TakeAttendanceRoute: typeof TakeAttendanceRoute
  TasksRoute: typeof TasksRoute
  TimetableRoute: typeof TimetableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/take-attendance': {
      id: '/take-attendance'
      path: '/take-attendance'
      fullPath: '/take-attendance'
      preLoaderRoute: typeof TakeAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payslips': {
      id: '/payslips'
      path: '/payslips'
      fullPath: '/payslips'
      preLoaderRoute: typeof PayslipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-leave': {
      id: '/my-leave'
      path: '/my-leave'
      fullPath: '/my-leave'
      preLoaderRoute: typeof MyLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-grades': {
      id: '/my-grades'
      path: '/my-grades'
      fullPath: '/my-grades'
      preLoaderRoute: typeof MyGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-fees': {
      id: '/my-fees'
      path: '/my-fees'
      fullPath: '/my-fees'
      preLoaderRoute: typeof MyFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses': {
      id: '/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof MyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-classes': {
      id: '/my-classes'
      path: '/my-classes'
      fullPath: '/my-classes'
      preLoaderRoute: typeof MyClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-attendance': {
      id: '/my-attendance'
      path: '/my-attendance'
      fullPath: '/my-attendance'
      preLoaderRoute: typeof MyAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-assignments': {
      id: '/my-assignments'
      path: '/my-assignments'
      fullPath: '/my-assignments'
      preLoaderRoute: typeof MyAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries': {
      id: '/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof InquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradebook': {
      id: '/gradebook'
      path: '/gradebook'
      fullPath: '/gradebook'
      preLoaderRoute: typeof GradebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment': {
      id: '/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof EnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AssignmentsRoute: AssignmentsRoute,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  EnrollmentRoute: EnrollmentRoute,
  EventsRoute: EventsRoute,
  FeesRoute: FeesRoute,
  GradebookRoute: GradebookRoute,
  InquiriesRoute: InquiriesRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MyAssignmentsRoute: MyAssignmentsRoute,
  MyAttendanceRoute: MyAttendanceRoute,
  MyClassesRoute: MyClassesRoute,
  MyCoursesRoute: MyCoursesRoute,
  MyFeesRoute: MyFeesRoute,
  MyGradesRoute: MyGradesRoute,
  MyLeaveRoute: MyLeaveRoute,
  MyProfileRoute: MyProfileRoute,
  PayslipsRoute: PayslipsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  StudentsRoute: StudentsRoute,
  TakeAttendanceRoute: TakeAttendanceRoute,
  TasksRoute: TasksRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
